clear all;clc
%% contrast difference of different functions

startDate = '2002-06-23';
nAnnual = 6; nSeasonal = 5; day_lag = 4;
Slen = 3; % 3x3:24s, 5x5:29s, 7x7:37s
pbcrit = 0.01;
[nTime,nLon,nLat] = size(P);
lon = 100;
lat = 50;
independ_type = 1;
fun = 4;

tic
mains = main();
[p_value,impact,R2P,R2S,...
 RR,endogenity,...
 season_anomaly,POCC,S1,...
 independ_terms,residP,residS,...
 seasTerm,annualTerm] = ...
    mains.get_sp_impact...
          (P,S,press,...
           lon,lat,...
           startDate,...
           nAnnual,nSeasonal,day_lag,...
           Slen,...
           pbcrit,...
           fun,...
           independ_type);
toc

[p,spImpact,in,Sclim_aic,poccR2,sR2,POCC,sNew,seasTerm,jd,poccPredict,sPredict] = ...
    spImpactRankOfrandomForestNew(P(:,lon,lat),S(:,lon,lat),press(:,lon,lat));
