clear all;clc;
%
load('Data/NCA-LDAS.mat')
startDate = '2002-06-19';
nAnnual = 6; nSeasonal = 5; day_lag = 4;
Slen = 3; % 3x3:24s, 5x5:29s, 7x7:37s
pbcrit = 0.01;
[nTime,nLon,nLat] = size(P);
lon = 100;
lat = 50;
tic
[p_value,impact,R2P,R2S,season_anomaly,POCC,S,independ_terms,residP,residS,seasTerm] = main(P,S,press,...
                        lon,lat,...
                        startDate,...
                        nAnnual,nSeasonal,day_lag,...
                        Slen,...
                        pbcrit);
toc
tic
[p,spImpact,in,Sclim_aic,poccR2,sR2,POCC1,S2,seasTerm,jd1,pPredict,sPredict] = spImpactRankOfrandomForestNew(P(:,lon,lat),...
                                             S(:,lon,lat),...
                                             press(:,lon,lat));
toc
